spring:
  application:
    name: spring-sidecar
server:
  port: 8212
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://222.73.239.52:2221/eureka
       defaultZone: http://61.160.207.86:2221/eureka
    healthcheck:  # 健康检查
      enabled: true

#####################################################################################################
# 异构微服务的配置， port 代表异构微服务的端口；health-uri 代表异构微服务的操作链接地址
sidecar:
  port: 80
  health-uri: http://localhost:80/health.json    #此处为非java服务端的一个接口地址，返回必须为 {"status": "UP"}，用着eureka监听
#####################################################################################################

##Sidecar应用程序必须和第三方应用程序运行在同一台电脑上，也就是说他们之间是localhost，不能是ip访问（官网未提及）
