spring:
  application:
    name: spring-zuul
server:
  port: 80

eureka:
  client:
    service-url:
#      defaultZone: http://222.73.239.52:2221/eureka61.160.207.86
       defaultZone: http://61.160.207.86:2221/eureka
    healthcheck:  # 健康检查
      enabled: true

#  调用spring-sidecar 实现轮询调用
zuul:
  routes:
     api-1:
       path: /**
       serviceId: spring-sidecar